# Generated by Django 5.2.15 on 2026-07-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.CharField(default='alipnm110', max_length=100),
            preserve_default=False,
        ),
    ]
